# Generated by Django 3.2.3 on 2021-05-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='univer.basic_menu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='univer.category'),
        ),
    ]
