# Generated by Django 3.2.3 on 2021-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_auto_20210531_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quest',
            field=models.IntegerField(default=0),
        ),
    ]
