# Generated by Django 3.2.3 on 2021-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0003_category_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quest',
        ),
        migrations.AddField(
            model_name='teacher',
            name='quest',
            field=models.IntegerField(default=1),
        ),
    ]
