# Generated by Django 3.2.3 on 2021-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0004_auto_20210603_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quest', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='quest',
        ),
    ]
